# BASIC OF NUMPY

In [1]:
## Numpy is used for numerical operations

In [2]:
## array is a collection of data ....array is like list but array is n dimensional

In [3]:
## size is known as shape in array, shape means dimension..

In [4]:
## (x,x) first is always row and second is always column ## [Row,Column]

In [5]:
## array is strictly n dimensional and matrix is 2 dimensional

In [2]:
import numpy as np

In [7]:
## define an 1d array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
## Checking the shape
arr1.shape

(5,)

In [10]:
## operation on 1d array

In [11]:
## sum 
arr1.sum() ## sum the entire array

15

In [12]:
arr1.mean() ## mean of the array

3.0

In [13]:
arr1.std()

1.4142135623730951

In [14]:
## create an 2d array

In [19]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [20]:
arr2.shape ## (row,column)

(5,)

In [22]:
arr3 = np.array([[1,2,3],[4,5,6]])

In [23]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr3[:] ## entire arr all rows all columns arr3[row,column]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr3.shape

(2, 3)

In [27]:
arr4 = np.array([[4,5,6,7,8,],[9,8,7,6,5]])
arr4

array([[4, 5, 6, 7, 8],
       [9, 8, 7, 6, 5]])

In [28]:
arr4.shape

(2, 5)

In [29]:
## [:] means select all

In [32]:
arr3[:] ## Entire arr all rows all columns arr3[rows,column]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr3[:,0] ## All rows of 1st index column : >all rows, 1 > mean column at 1 index

array([1, 4])

In [34]:
arr3[0,:] ## 0=> 0th row and all columns

array([1, 2, 3])

In [35]:
arr3[0,2] = 99 ## postion 0,2

In [36]:
arr3

array([[ 1,  2, 99],
       [ 4,  5,  6]])

In [37]:
arr3.shape

(2, 3)

In [38]:
## row is known by axis=1, column is known by axis = 0

In [39]:
## if you want to add,sum,mean,max etc column wise or row wise you have to use axis

In [40]:
## mean output is always in float

In [41]:
arr3.sum(axis=0)

array([  5,   7, 105])

In [42]:
arr3.sum(axis=1)

array([102,  15])

In [43]:
arr3.mean(axis=0)

array([ 2.5,  3.5, 52.5])

In [44]:
arr3.mean(axis=1)

array([34.,  5.])

In [45]:
arr3.max(axis=1)

array([99,  6])

In [46]:
arr3.max(axis=0)

array([ 4,  5, 99])

In [47]:
arr3

array([[ 1,  2, 99],
       [ 4,  5,  6]])

In [48]:
arr3.argmax(axis=0) ## gives index of maximum value in each column

array([1, 1, 0], dtype=int64)

In [50]:
arr3.argmax(axis=1) ## gives index of maximum value in each row

array([2, 2], dtype=int64)

In [51]:
arr3.min(axis=0)

array([1, 2, 6])

In [52]:
arr3.min(axis=1)

array([1, 4])

In [53]:
arr3.argmin(axis=0) ## gives index of minimum value in each column

array([0, 0, 1], dtype=int64)

In [54]:
arr4 = np.random.rand(3,4)
arr4

array([[0.6451589 , 0.63021014, 0.70291725, 0.9058149 ],
       [0.03193094, 0.53877613, 0.59858039, 0.13285459],
       [0.92061344, 0.63761073, 0.07398183, 0.86489128]])

In [55]:
arr4.reshape(4,3) ## arr.reshape(row,column) ## while reshape the multiply should be same for eg now the multiply is 12

array([[0.6451589 , 0.63021014, 0.70291725],
       [0.9058149 , 0.03193094, 0.53877613],
       [0.59858039, 0.13285459, 0.92061344],
       [0.63761073, 0.07398183, 0.86489128]])

In [56]:
arr4.reshape(1,-1) ## change shape to 1 row and adjust element auto

array([[0.6451589 , 0.63021014, 0.70291725, 0.9058149 , 0.03193094,
        0.53877613, 0.59858039, 0.13285459, 0.92061344, 0.63761073,
        0.07398183, 0.86489128]])

In [57]:
arr4.reshape(-1,1) ## -1 means nothing

array([[0.6451589 ],
       [0.63021014],
       [0.70291725],
       [0.9058149 ],
       [0.03193094],
       [0.53877613],
       [0.59858039],
       [0.13285459],
       [0.92061344],
       [0.63761073],
       [0.07398183],
       [0.86489128]])

# SCALER OPERATION ON ARRAY

In [58]:
arr4*100

array([[64.51589005, 63.02101435, 70.29172535, 90.58149049],
       [ 3.19309406, 53.8776129 , 59.85803928, 13.28545852],
       [92.06134404, 63.7610727 ,  7.39818342, 86.48912824]])

In [59]:
arr4/100

array([[0.00645159, 0.0063021 , 0.00702917, 0.00905815],
       [0.00031931, 0.00538776, 0.0059858 , 0.00132855],
       [0.00920613, 0.00637611, 0.00073982, 0.00864891]])

In [60]:
arr4 - arr4.max()

array([[-0.27545454, -0.2904033 , -0.21769619, -0.01479854],
       [-0.8886825 , -0.38183731, -0.32203305, -0.78775886],
       [ 0.        , -0.28300271, -0.84663161, -0.05572216]])

In [61]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr6 = np.array([[1,2],[3,4],[5,6]])
arr6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
arr5+arr6 ## error cause dimensions should be same

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [65]:
arr6 = np.array([[1,2,5],[3,4,5],[5,6,8]])
arr6

array([[1, 2, 5],
       [3, 4, 5],
       [5, 6, 8]])

In [66]:
arr5 + arr6

array([[ 2,  4,  8],
       [ 7,  9, 11],
       [12, 14, 17]])

In [67]:
arr5*arr6

array([[ 1,  4, 15],
       [12, 20, 30],
       [35, 48, 72]])

In [68]:
arr5 - arr6

array([[ 0,  0, -2],
       [ 1,  1,  1],
       [ 2,  2,  1]])

In [69]:
arr5**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

# TRIGNOMETRIC OPERATION

In [70]:
np.pi

3.141592653589793

In [71]:
np.sin(0)

0.0

In [72]:
np.sin(0) ## radian

0.0

In [73]:
np.sin(90*(np.pi/180)) ## degree

1.0

In [74]:
np.cos(0)

1.0

In [75]:
np.cos(90*(np.pi/100)) ## approximate equals to 0 since np.pi is a irrational number

-0.9510565162951536

In [76]:
np.sin(np.deg2rad(90)) ## Direct fn to convert degree to rad

1.0

In [77]:
np.cos(np.deg2rad(90))

6.123233995736766e-17

In [78]:
np.tan(np.deg2rad(45))

0.9999999999999999

In [79]:
np.sin(np.deg2rad(45))/np.cos(np.deg2rad(45))

1.0

# ROUNDING OPERATION

In [80]:
a = 1.27935
b = -1.2578

In [81]:
np.abs(b)

1.2578

In [83]:
np.round(a,2) ## Round to 2 decisions places

1.28

In [84]:
np.round(b,2)

-1.26

In [86]:
np.ceil(a) ## Ceil to next higher integer

2.0

In [87]:
np.trunc(a) ## ceil to previous lower integer

1.0

In [88]:
np.trunc(b) ## negative

-1.0

In [89]:
np.ceil(b)

-1.0

In [90]:
## to take help on a function use below methods

In [91]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

# MATRIX OPERATIONS

In [4]:
m1 = np.matrix([[1,2,3],[4,5,6],[2,4,6]])
m2 = np.matrix([[9,8,7],[8,3,2],[2,3,4]])

In [5]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 6]])

In [6]:
m2

matrix([[9, 8, 7],
        [8, 3, 2],
        [2, 3, 4]])

In [7]:
type(m1)

numpy.matrix

In [8]:
m1.shape

(3, 3)

In [9]:
m1*m2

matrix([[31, 23, 23],
        [88, 65, 62],
        [62, 46, 46]])

In [10]:
m1 - m2

matrix([[-8, -6, -4],
        [-4,  2,  4],
        [ 0,  1,  2]])

In [11]:
m1 + m2

matrix([[10, 10, 10],
        [12,  8,  8],
        [ 4,  7, 10]])

In [12]:
m1 * 2

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [ 4,  8, 12]])

In [14]:
np.matmul(m1,m2)

matrix([[31, 23, 23],
        [88, 65, 62],
        [62, 46, 46]])

In [19]:
m1.T

matrix([[1, 4, 2],
        [2, 5, 4],
        [3, 6, 6]])

In [17]:
m2.T

matrix([[9, 8, 2],
        [8, 3, 3],
        [7, 2, 4]])

In [20]:
np.linalg.det(m1)

0.0

In [21]:
np.linalg.det(m2)

-44.000000000000014

In [22]:
m3 = np.matrix([[1,2,3],[1,1,0],[1,2,1]])

In [23]:
m3

matrix([[1, 2, 3],
        [1, 1, 0],
        [1, 2, 1]])

In [24]:
np.linalg.inv(m3)#

matrix([[ 0.5,  2. , -1.5],
        [-0.5, -1. ,  1.5],
        [ 0.5, -0. , -0.5]])

In [25]:
np.linalg.det(m3)

2.0

In [27]:
## Some more on matrices

In [28]:
m = np.matrix([[1,4],[3,2]])
m

matrix([[1, 4],
        [3, 2]])

In [29]:
np.linalg.eigvals(m) ## Getting Eigne Values

array([-2.,  5.])

In [30]:
m = np.matrix([[2,0,0],[0,4,5],[0,4,3]])
m

matrix([[2, 0, 0],
        [0, 4, 5],
        [0, 4, 3]])

In [31]:
np.linalg.eig(m)

(array([-1.,  8.,  2.]),
 matrix([[ 0.        ,  0.        ,  1.        ],
         [ 0.70710678, -0.78086881,  0.        ],
         [-0.70710678, -0.62469505,  0.        ]]))

In [32]:
## Rank of matrix

In [33]:
## Rank = no. of non zeros rows

In [34]:
np.linalg.matrix_rank(m1)

2

In [35]:
m2 = np.matrix([[1,2,3],[2,4,6],[5,7,8]])
m2

matrix([[1, 2, 3],
        [2, 4, 6],
        [5, 7, 8]])

In [36]:
np.linalg.matrix_rank(m2)

2

In [37]:
np.ones((3,3)) ## Creating array with all ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.zeros ((3,3)) ## Creating array with all zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
arr = np.array([[1,2,3],[4,5,6],[2,4,6]])

In [40]:
np.linalg.det(arr)

0.0

In [41]:
np.identity(2) ## Identity Matrix

array([[1., 0.],
       [0., 1.]])

In [42]:
np.random.choice([1,2,3,4,5,6]) ## Choose on element randomly

6

In [45]:
np.random.choice(["A","B","C","D"]) ## Choose an element randomly

'D'

In [47]:
np.array([[1,2,"A"],[2,3,"C"],[1,2,3]]) ## Multi datatype in array

array([['1', '2', 'A'],
       ['2', '3', 'C'],
       ['1', '2', '3']], dtype='<U11')

In [48]:
np.matrix([[1,2,"A"],[2,3,"C"],[1,2,3]]) ## U11 shows unicode datatype

matrix([['1', '2', 'A'],
        ['2', '3', 'C'],
        ['1', '2', '3']], dtype='<U11')